// src/components/UtilitySection/UtilitySection.tsx
import { Button } from 'ui';
import { styles } from './UtilitySection.styles';
import { useClasses } from 'hooks';
import { Container, Grid, Paper, Stack } from '@mui/material';
import Carousel from 'react-multi-carousel';
import 'react-multi-carousel/lib/styles.css';

export const UtilitySection = () => {
    const {
        container,
        leftContainer,
        subTitleText,
        titleText,
        mainText
    } = useClasses(styles);

    const responsive = {
        superLargeDesktop: {
            // the naming can be any, depends on you.
            breakpoint: { max: 4000, min: 3000 },
            items: 1
        },
        desktop: {
            breakpoint: { max: 3000, min: 1024 },
            items: 1
        },
        tablet: {
            breakpoint: { max: 1024, min: 464 },
            items: 1
        },
        mobile: {
            breakpoint: { max: 464, min: 0 },
            items: 1
        }
    }

    return (
        <div className={container}>
            <p className={titleText}>UTILITY</p>
            <Carousel
                arrows={false}
                swipeable={true}
                draggable={false}
                showDots={false}
                responsive={responsive}
                ssr={true} // means to render carousel on server-side.
                infinite={true}
                autoPlay={true}
                autoPlaySpeed={3000}
                keyBoardControl={true}
                transitionDuration={500}
                containerClass="carousel-container"
                removeArrowOnDeviceType={["tablet", "mobile"]}
                dotListClass="custom-dot-list-style"
                itemClass="carousel-item-padding-40-px"
            >
                <div style={{ width: "100%" }}>
                    <Grid container spacing={0}>
                        <Grid item xs={6} className={leftContainer} >
                            <p className={subTitleText}>Into the Buddieverse</p>
                            <p className={mainText}>Our own 3D metaverse full of fun and utility.</p>
                            <p className={mainText}>Walk into Buddieverse, play games, buy composable NFTs, learn in the University, read our official comic in the kiosk, bet in the Casino, promote your business on the billboards or even order your own building. You can do everything in Buddies St.</p>
                        </Grid>
                        <Grid item xs={6} style={{textAlign: "center"}}>
                            <img
                                src="./utility (1).png"
                                style={{ width: "100%"}}
                            />
                        </Grid>
                    </Grid>
                </div>
                <div style={{ width: "100%" }}>
                    <Grid container spacing={0}>
                        <Grid item xs={6} className={leftContainer} >
                            <p className={subTitleText}>Alpha trading</p>
                            <p className={mainText}>BUDDIES have access to professional trading calls provided for free. With an 80% success rate, BAT users can recoup their investment and continue to profit</p>
                        </Grid>
                        <Grid item xs={6} style={{textAlign: "center"}}>
                            <img
                                src="./utility (2).png"
                                style={{ width: "100%"}}
                            />
                        </Grid>
                    </Grid>
                </div>
                <div style={{ width: "100%" }}>
                    <Grid container spacing={0}>
                        <Grid item xs={6} className={leftContainer} >
                            <p className={subTitleText}>Buddies capital</p>
                            <p className={mainText}>BUDDIES can share investment ideas with fellow holders. If the idea passes with a governance vote, the proposing BUDDIE will get 20% of the profits with the rest going to the community bank</p>
                        </Grid>
                        <Grid item xs={6} style={{textAlign: "center"}}>
                            <img
                                src="./utility (3).png"
                                style={{ width: "100%"}}
                            />
                        </Grid>
                    </Grid>
                </div>
                <div style={{ width: "100%" }}>
                    <Grid container spacing={0}>
                        <Grid item xs={6} className={leftContainer} >
                            <p className={subTitleText}>Public library</p>
                            <p className={mainText}>BUDDIES love to learn, and we share knowledge pertaining to blockchain technology, trading, coding, and so much more within a dedicated channel</p>
                        </Grid>
                        <Grid item xs={6} style={{textAlign: "center"}}>
                            <img
                                src="./utility (4).png"
                                style={{ width: "100%"}}
                            />
                        </Grid>
                    </Grid>
                </div>
                <div style={{ width: "100%" }}>
                    <Grid container spacing={0}>
                        <Grid item xs={6} className={leftContainer} >
                            <p className={subTitleText}>NFT staking</p>
                            <p className={mainText}>Stake your BUDDIE NFT to receive Buddieverse resources. These can be used to purchase merchandise, join raffles, and more!</p>
                        </Grid>
                        <Grid item xs={6} style={{textAlign: "center"}}>
                            <img
                                src="./utility (5).png"
                                style={{ width: "100%"}}
                            />
                        </Grid>
                    </Grid>
                </div>
            </Carousel>
        </div>
    );
};

// src/views/UtilitySection.vue
<template>
  <section>
    <p class="font-size-96-green mt-5 has-text-centered">UTILITY</p>
    <b-carousel
      :arrow="false"
      :draggable="true"
    >
      <b-carousel-item v-for="(item, i) in items" :key="i">
        <div class="columns mt-4 mb-5 ml-5">
          <div class="column is-6">
            <p class="font-size-96">
              {{ item.title }}
            </p>
            <p class="font-size-24 mt-4">
              {{ item.description }}
            </p>
          </div>
          <div class="column is-6">
            <img :src="item.image" alt="No Image" class="fix-height-image" />
          </div>
        </div>
      </b-carousel-item>
    </b-carousel>
  </section>
</template>

<script>
import { Component, Vue, Watch } from "vue-property-decorator";
import VueMetamask from "vue-metamask";

@Component({
  components: {
    VueMetamask,
  },
})
export default class UtilitySection extends Vue {
  items = [
    {
      title: "Into the Buddieverse",
      description:
        "Our own 3D metaverse full of fun and utility. Walk into Buddieverse, play games, buy composable NFTs, learn in the University, read our official comic in the kiosk, bet in the Casino, promote your business on the billboards or even order your own building. You can do everything in Buddies St.",
      image: require("@/assets/utility/0.png"),
    },
    {
      title: "Alpha trading",
      description:
        "BUDDIES have access to professional trading calls provided for free. With an 80% success rate, BAT users can recoup their investment and continue to profit",
      image: require("@/assets/utility/1.png"),
    },
    {
      title: "Buddies capital",
      description:
        "BUDDIES can share investment ideas with fellow holders. If the idea passes with a governance vote, the proposing BUDDIE will get 20% of the profits with the rest going to the community bank",
      image: require("@/assets/utility/2.png"),
    },
    {
      title: "Public library",
      description:
        "BUDDIES love to learn, and we share knowledge pertaining to blockchain technology, trading, coding, and so much more within a dedicated channel",
      image: require("@/assets/utility/3.png"),
    },
    {
      title: "NFT staking",
      description:
        "Stake your BUDDIE NFT to receive Buddieverse resources. These can be used to purchase merchandise, join raffles, and more!",
      image: require("@/assets/utility/4.png"),
    },
  ];
}
</script>

<style lang="scss">
@import "~bulma/sass/utilities/_all";
</style>
